### ISSUE TITLE
What is the atlases folder

### ISSUE THREAD

**Issue by lintianfang** [facebookresearch/Replica-Dataset#72]
I compile the SDK ubuntu 18.04, when I run "./build/ReplicaSDK/ReplicaViewer ./data/apartment_0/mesh.ply textures ./data/apartment_0/glass.sur"

There is an error "Assert failed: pangolin::FileExists(atlasFolder), /home/ltf/Desktop/Replica-Dataset/ReplicaSDK/src/viewer.cpp:17
"

does anyone know what is the issue here?

Thanks very much!

**Comment by liustu** [comment]
Hi, have you solve this problem？
I have met the same problem,
(base) ycb@ycb:~/Replica-Dataset-main$ ./build/ReplicaSDK/ReplicaRenderer mesh.ply textures glass.sur
./build/ReplicaSDK/ReplicaRenderer: error while loading shared libraries: libtinyobj.so: cannot open shared object file: No such file or directory

**Comment by lintianfang** [comment]
> 
> 
> Hi, have you solve this problem？ I have met the same problem, (base) ycb@ycb:~/Replica-Dataset-main$ ./build/ReplicaSDK/ReplicaRenderer mesh.ply textures glass.sur ./build/ReplicaSDK/ReplicaRenderer: error while loading shared libraries: libtinyobj.so: cannot open shared object file: No such file or directory

Not yet, do you have any idea?

**Comment by liustu** [comment]
I&nbsp; &nbsp;haven't solve this problem.



---Original---
From: ***@***.***&gt;
Date: Wed, Nov 3, 2021 00:24 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [facebookresearch/Replica-Dataset] What is the atlases folder(Issue #72)




  
Hi, have you solve this problem？ I have met the same problem, (base) ***@***.***:~/Replica-Dataset-main$ ./build/ReplicaSDK/ReplicaRenderer mesh.ply textures glass.sur ./build/ReplicaSDK/ReplicaRenderer: error while loading shared libraries: libtinyobj.so: cannot open shared object file: No such file or directory
  
Not yet, do you have any idea?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sukun1045** [comment]
Hi guys, I also encounter the same problem. The `textures` here should be a folder containing the `hdr` files. It should work if you try: `./build/ReplicaSDK/ReplicaViewer ./data/apartment_0/mesh.ply ./data/apartment_0/textures/ ./data/apartment_0/glass.sur`

**Comment by lintianfang** [comment]
> Hi guys, I also encounter the same problem. The `textures` here should be a folder containing the `hdr` files. It should work if you try: `./build/ReplicaSDK/ReplicaViewer ./data/apartment_0/mesh.ply ./data/apartment_0/textures/ ./data/apartment_0/glass.sur`

Thank you very much!
